;
;	This file is automatically generated
;

graphicsIntegrated = 1

	.include	"./aa.main/aa.data.asm"
	.include	"./aa.main/main.asm"
	.include	"./aa.main/vectors.asm"
	.include	"./drawing/circle.asm"
	.include	"./drawing/clear.asm"
	.include	"./drawing/control.asm"
	.include	"./drawing/line.asm"
	.include	"./drawing/mode.asm"
	.include	"./drawing/plot.asm"
	.include	"./drawing/rect.asm"
	.include	"./drawing/render.asm"
	.include	"./drawing/sources/font.asm"
	.include	"./drawing/sources/sprite.asm"
	.include	"./drawing/sprite.asm"
	.include	"./utility/access.asm"
	.include	"./utility/calculate.asm"
	.include	"./utility/collide.asm"
	.include	"./utility/find.asm"
	.include	"./utility/sort.asm"
