; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		colours.inc
;		Purpose:	Console colour scheme
;		Created:	17th November 2022
;		Reviewed: 	
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

CONBlack = 0
CONWhite = 1
CONRed = 2
CONCyan = 3
CONPurple = 4
CONGreen = 5
CONBlue = 6
CONYellow = 7
CONOrange = 8
CONBrown = 9
CONYellowGreen = 10
CONRosa = 11
CONBlueGreen = 12
CONLightBlue = 13
CONPink = 14
CONLightGreen = 15

CONForeground = CONYellow
CONBackground = CONBlue

CLICommandLine = CONGreen

CLIFComment = CONBlack
CLIBComment = CONYellow

CLINumber = CONBrown
CLIToken = CONCyan
CLIConstant = CONLightBlue
CLIIdentifier = CONYellow
CLIPunctuation = CONYellowGreen
CLIData = CONWhite

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
