# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		scancodes.py
#		Purpose :	Scan the graphics file for the markers for graphics comands
#		Date :		14th November 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,re

sourceFiles = []																			# source files in order
includeFiles = []

for root,dirs,files in os.walk("."): 														# scan for directories
	for f in files: 																		# look for files that are .asm
		if f != "_graphics.asm":
			fName = root + os.sep + f
			if fName.endswith(".asm"):
				sourceFiles.append(fName)
			if fName.endswith(".inc"):
				includeFiles.append(fName)
includeFiles.sort()			
sourceFiles.sort()
#
#		Scan files for codes.
#
codes = {}
highCode = 0
for f in sourceFiles:
	for s in open(f).readlines():
		if s.find(";;") > 0:
			m = re.match("^(.*?)\\:\\s*\\;\\;\\s*\\<(\\d+)\\:(.*?)\\>",s)
			assert m is not None,s+" bad"
			n = int(m.group(2))
			assert n not in codes,"Duplicate "+s
			codes[n] = [m.group(1),m.group(3)]
			highCode = max(highCode,n)
#
#		Write out vector table
#			
h = open("aa.main/_vectors.asm","w")
h.write(";\n;\tThis file is automatically generated\n;\n")
h.write("\nGRFirstFreeCode = {0}\n\n".format(highCode+1))
h.write("\t.section code\n")
h.write("GRVectorTable:\n")
for i in range(0,highCode+1):
	if i in codes:
		h.write("\t.word\t{0:24} ; ${1:02x} {2}\n".format(codes[i][0],i,codes[i][1]))
	else:
		h.write("\t.word\t{0:24} ; ${1:02x}\n".format("GRUndefined",i))
h.write("\t.send code\n")
h.close()			
#
#		Write out constants file.
#
h = open("aa.main/_graphics.inc","w")
h.write(";\n;\tThis file is automatically generated\n;\n")
for i in range(0,highCode+1):
	if i in codes:
		h.write("GCMD_{0} = {1}*2\n".format(codes[i][1],i))
h.close()			
