;
;	This is automatically generated.
;
	.section code
KeywordSet0:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	4,$fe,"ABS("           ; $83 ABS(
	.text	6,$93,"ALLOC("         ; $84 ALLOC(
	.text	4,$ff,"ASC("           ; $85 ASC(
	.text	5,$29,"CHR$("          ; $86 CHR$(
	.text	6,$aa,"EVENT("         ; $87 EVENT(
	.text	5,$6b,"FALSE"          ; $88 FALSE
	.text	5,$44,"FRAC("          ; $89 FRAC(
	.text	9,$4a,"GETDATE$("      ; $8a GETDATE$(
	.text	9,$5b,"GETTIME$("      ; $8b GETTIME$(
	.text	4,$0d,"HIT("           ; $8c HIT(
	.text	4,$13,"INT("           ; $8d INT(
	.text	6,$a7,"ISVAL("         ; $8e ISVAL(
	.text	5,$5c,"JOYB("          ; $8f JOYB(
	.text	5,$72,"JOYX("          ; $90 JOYX(
	.text	5,$73,"JOYY("          ; $91 JOYY(
	.text	6,$77,"LEFT$("         ; $92 LEFT$(
	.text	4,$07,"LEN("           ; $93 LEN(
	.text	4,$0e,"MAX("           ; $94 MAX(
	.text	5,$26,"MID$("          ; $95 MID$(
	.text	4,$0c,"MIN("           ; $96 MIN(
	.text	4,$19,"NOT("           ; $97 NOT(
	.text	5,$4d,"PEEK("          ; $98 PEEK(
	.text	6,$91,"PEEKD("         ; $99 PEEKD(
	.text	6,$99,"PEEKL("         ; $9a PEEKL(
	.text	6,$a4,"PEEKW("         ; $9b PEEKW(
	.text	8,$3c,"PLAYING("       ; $9c PLAYING(
	.text	7,$e9,"RANDOM("        ; $9d RANDOM(
	.text	7,$ca,"RIGHT$("        ; $9e RIGHT$(
	.text	4,$0c,"RND("           ; $9f RND(
	.text	4,$10,"SGN("           ; $a0 SGN(
	.text	4,$0e,"SPC("           ; $a1 SPC(
	.text	5,$45,"STR$("          ; $a2 STR$(
	.text	6,$a9,"TIMER("         ; $a3 TIMER(
	.text	4,$40,"TRUE"           ; $a4 TRUE
	.text	4,$0b,"VAL("           ; $a5 VAL(
	.text	3,$e7,"FOR"            ; $a6 FOR
	.text	2,$8f,"IF"             ; $a7 IF
	.text	4,$34,"PROC"           ; $a8 PROC
	.text	6,$c1,"REPEAT"         ; $a9 REPEAT
	.text	5,$79,"WHILE"          ; $aa WHILE
	.text	5,$66,"ENDIF"          ; $ab ENDIF
	.text	7,$0b,"ENDPROC"        ; $ac ENDPROC
	.text	4,$3f,"NEXT"           ; $ad NEXT
	.text	4,$2f,"THEN"           ; $ae THEN
	.text	5,$8c,"UNTIL"          ; $af UNTIL
	.text	4,$2e,"WEND"           ; $b0 WEND
	.text	2,$9b,"BY"             ; $b1 BY
	.text	4,$1c,"CALL"           ; $b2 CALL
	.text	6,$b2,"CIRCLE"         ; $b3 CIRCLE
	.text	5,$67,"CLEAR"          ; $b4 CLEAR
	.text	3,$e2,"CLS"            ; $b5 CLS
	.text	5,$7f,"COLOR"          ; $b6 COLOR
	.text	6,$d4,"COLOUR"         ; $b7 COLOUR
	.text	6,$d0,"CPRINT"         ; $b8 CPRINT
	.text	4,$1a,"DATA"           ; $b9 DATA
	.text	3,$da,"DIM"            ; $ba DIM
	.text	6,$db,"DOWNTO"         ; $bb DOWNTO
	.text	4,$29,"ELSE"           ; $bc ELSE
	.text	4,$34,"FROM"           ; $bd FROM
	.text	3,$e5,"GFX"            ; $be GFX
	.text	5,$80,"GOSUB"          ; $bf GOSUB
	.text	4,$39,"GOTO"           ; $c0 GOTO
	.text	4,$24,"HERE"           ; $c1 HERE
	.text	5,$63,"IMAGE"          ; $c2 IMAGE
	.text	5,$90,"INPUT"          ; $c3 INPUT
	.text	3,$e5,"LET"            ; $c4 LET
	.text	4,$28,"LINE"           ; $c5 LINE
	.text	5,$6b,"LOCAL"          ; $c6 LOCAL
	.text	3,$db,"OFF"            ; $c7 OFF
	.text	2,$9d,"ON"             ; $c8 ON
	.text	7,$20,"OUTLINE"        ; $c9 OUTLINE
	.text	7,$0f,"PALETTE"        ; $ca PALETTE
	.text	4,$3f,"PLOT"           ; $cb PLOT
	.text	4,$2f,"POKE"           ; $cc POKE
	.text	5,$73,"POKED"          ; $cd POKED
	.text	5,$7b,"POKEL"          ; $ce POKEL
	.text	5,$86,"POKEW"          ; $cf POKEW
	.text	5,$8d,"PRINT"          ; $d0 PRINT
	.text	4,$1c,"READ"           ; $d1 READ
	.text	4,$2e,"RECT"           ; $d2 RECT
	.text	3,$e4,"REM"            ; $d3 REM
	.text	6,$e0,"RETURN"         ; $d4 RETURN
	.text	5,$7b,"SOLID"          ; $d5 SOLID
	.text	5,$89,"SOUND"          ; $d6 SOUND
	.text	6,$d7,"SPRITE"         ; $d7 SPRITE
	.text	4,$45,"TEXT"           ; $d8 TEXT
	.text	2,$a3,"TO"             ; $d9 TO
	.text	$FF
KeywordSet1:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	8,$4c,"ASSEMBLE"       ; $83 ASSEMBLE
	.text	6,$d2,"ASSERT"         ; $84 ASSERT
	.text	6,$bd,"BITMAP"         ; $85 BITMAP
	.text	5,$62,"BLOAD"          ; $86 BLOAD
	.text	5,$71,"BSAVE"          ; $87 BSAVE
	.text	3,$df,"DIR"            ; $88 DIR
	.text	5,$7a,"DRIVE"          ; $89 DRIVE
	.text	3,$d7,"END"            ; $8a END
	.text	7,$11,"EXPLODE"        ; $8b EXPLODE
	.text	2,$96,"GO"             ; $8c GO
	.text	5,$70,"HIMEM"          ; $8d HIMEM
	.text	4,$3c,"LIST"           ; $8e LIST
	.text	4,$20,"LOAD"           ; $8f LOAD
	.text	3,$ea,"NEW"            ; $90 NEW
	.text	4,$2e,"PING"           ; $91 PING
	.text	7,$24,"RESTORE"        ; $92 RESTORE
	.text	3,$f5,"RUN"            ; $93 RUN
	.text	4,$2f,"SAVE"           ; $94 SAVE
	.text	7,$0a,"SETDATE"        ; $95 SETDATE
	.text	7,$1b,"SETTIME"        ; $96 SETTIME
	.text	5,$8d,"SHOOT"          ; $97 SHOOT
	.text	7,$2a,"SPRITES"        ; $98 SPRITES
	.text	4,$46,"STOP"           ; $99 STOP
	.text	6,$d5,"VERIFY"         ; $9a VERIFY
	.text	3,$ee,"XGO"            ; $9b XGO
	.text	5,$78,"XLOAD"          ; $9c XLOAD
	.text	3,$eb,"ZAP"            ; $9d ZAP
	.text	$FF
KeywordSet2:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	3,$c8,"ADC"            ; $83 ADC
	.text	3,$d3,"AND"            ; $84 AND
	.text	3,$e0,"ASL"            ; $85 ASL
	.text	3,$c8,"BCC"            ; $86 BCC
	.text	3,$d8,"BCS"            ; $87 BCS
	.text	3,$d8,"BEQ"            ; $88 BEQ
	.text	3,$df,"BIT"            ; $89 BIT
	.text	3,$d8,"BMI"            ; $8a BMI
	.text	3,$d5,"BNE"            ; $8b BNE
	.text	3,$de,"BPL"            ; $8c BPL
	.text	3,$d5,"BRA"            ; $8d BRA
	.text	3,$df,"BRK"            ; $8e BRK
	.text	3,$db,"BVC"            ; $8f BVC
	.text	3,$eb,"BVS"            ; $90 BVS
	.text	3,$d2,"CLC"            ; $91 CLC
	.text	3,$d3,"CLD"            ; $92 CLD
	.text	3,$d8,"CLI"            ; $93 CLI
	.text	3,$e5,"CLV"            ; $94 CLV
	.text	3,$e0,"CMP"            ; $95 CMP
	.text	3,$eb,"CPX"            ; $96 CPX
	.text	3,$ec,"CPY"            ; $97 CPY
	.text	3,$cc,"DEC"            ; $98 DEC
	.text	3,$e1,"DEX"            ; $99 DEX
	.text	3,$e2,"DEY"            ; $9a DEY
	.text	3,$e6,"EOR"            ; $9b EOR
	.text	3,$da,"INC"            ; $9c INC
	.text	3,$ef,"INX"            ; $9d INX
	.text	3,$f0,"INY"            ; $9e INY
	.text	3,$e7,"JMP"            ; $9f JMP
	.text	3,$ef,"JSR"            ; $a0 JSR
	.text	3,$d1,"LDA"            ; $a1 LDA
	.text	3,$e8,"LDX"            ; $a2 LDX
	.text	3,$e9,"LDY"            ; $a3 LDY
	.text	3,$f1,"LSR"            ; $a4 LSR
	.text	3,$ed,"NOP"            ; $a5 NOP
	.text	3,$e2,"ORA"            ; $a6 ORA
	.text	3,$d9,"PHA"            ; $a7 PHA
	.text	3,$e8,"PHP"            ; $a8 PHP
	.text	3,$f0,"PHX"            ; $a9 PHX
	.text	3,$f1,"PHY"            ; $aa PHY
	.text	3,$dd,"PLA"            ; $ab PLA
	.text	3,$ec,"PLP"            ; $ac PLP
	.text	3,$f4,"PLX"            ; $ad PLX
	.text	3,$f5,"PLY"            ; $ae PLY
	.text	3,$ed,"ROL"            ; $af ROL
	.text	3,$f3,"ROR"            ; $b0 ROR
	.text	3,$ef,"RTI"            ; $b1 RTI
	.text	3,$f9,"RTS"            ; $b2 RTS
	.text	3,$d8,"SBC"            ; $b3 SBC
	.text	3,$db,"SEC"            ; $b4 SEC
	.text	3,$dc,"SED"            ; $b5 SED
	.text	3,$e1,"SEI"            ; $b6 SEI
	.text	3,$e8,"STA"            ; $b7 STA
	.text	3,$f7,"STP"            ; $b8 STP
	.text	3,$ff,"STX"            ; $b9 STX
	.text	3,$00,"STY"            ; $ba STY
	.text	3,$01,"STZ"            ; $bb STZ
	.text	3,$ed,"TAX"            ; $bc TAX
	.text	3,$ee,"TAY"            ; $bd TAY
	.text	3,$e8,"TRB"            ; $be TRB
	.text	3,$e9,"TSB"            ; $bf TSB
	.text	3,$ff,"TSX"            ; $c0 TSX
	.text	3,$ed,"TXA"            ; $c1 TXA
	.text	3,$ff,"TXS"            ; $c2 TXS
	.text	3,$ee,"TYA"            ; $c3 TYA
	.text	$FF
	.send code
