;
;	This is automatically generated.
;
	.section code
KeywordSet0:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	4,$fe,"ABS("           ; $83 ABS(
	.text	6,$93,"ALLOC("         ; $84 ALLOC(
	.text	4,$ff,"ASC("           ; $85 ASC(
	.text	5,$29,"CHR$("          ; $86 CHR$(
	.text	6,$aa,"EVENT("         ; $87 EVENT(
	.text	5,$6b,"FALSE"          ; $88 FALSE
	.text	5,$44,"FRAC("          ; $89 FRAC(
	.text	5,$2c,"GET$("          ; $8a GET$(
	.text	4,$08,"GET("           ; $8b GET(
	.text	9,$4a,"GETDATE$("      ; $8c GETDATE$(
	.text	9,$5b,"GETTIME$("      ; $8d GETTIME$(
	.text	4,$0d,"HIT("           ; $8e HIT(
	.text	7,$cc,"INKEY$("        ; $8f INKEY$(
	.text	6,$a8,"INKEY("         ; $90 INKEY(
	.text	4,$13,"INT("           ; $91 INT(
	.text	6,$a7,"ISVAL("         ; $92 ISVAL(
	.text	5,$5c,"JOYB("          ; $93 JOYB(
	.text	5,$72,"JOYX("          ; $94 JOYX(
	.text	5,$73,"JOYY("          ; $95 JOYY(
	.text	6,$77,"LEFT$("         ; $96 LEFT$(
	.text	4,$07,"LEN("           ; $97 LEN(
	.text	4,$0e,"MAX("           ; $98 MAX(
	.text	5,$26,"MID$("          ; $99 MID$(
	.text	4,$0c,"MIN("           ; $9a MIN(
	.text	4,$19,"NOT("           ; $9b NOT(
	.text	5,$4d,"PEEK("          ; $9c PEEK(
	.text	6,$91,"PEEKD("         ; $9d PEEKD(
	.text	6,$99,"PEEKL("         ; $9e PEEKL(
	.text	6,$a4,"PEEKW("         ; $9f PEEKW(
	.text	8,$3c,"PLAYING("       ; $a0 PLAYING(
	.text	7,$e9,"RANDOM("        ; $a1 RANDOM(
	.text	7,$ca,"RIGHT$("        ; $a2 RIGHT$(
	.text	4,$0c,"RND("           ; $a3 RND(
	.text	4,$10,"SGN("           ; $a4 SGN(
	.text	4,$0e,"SPC("           ; $a5 SPC(
	.text	5,$45,"STR$("          ; $a6 STR$(
	.text	6,$a9,"TIMER("         ; $a7 TIMER(
	.text	4,$40,"TRUE"           ; $a8 TRUE
	.text	4,$0b,"VAL("           ; $a9 VAL(
	.text	3,$e7,"FOR"            ; $aa FOR
	.text	2,$8f,"IF"             ; $ab IF
	.text	4,$34,"PROC"           ; $ac PROC
	.text	6,$c1,"REPEAT"         ; $ad REPEAT
	.text	5,$79,"WHILE"          ; $ae WHILE
	.text	5,$66,"ENDIF"          ; $af ENDIF
	.text	7,$0b,"ENDPROC"        ; $b0 ENDPROC
	.text	4,$3f,"NEXT"           ; $b1 NEXT
	.text	4,$2f,"THEN"           ; $b2 THEN
	.text	5,$8c,"UNTIL"          ; $b3 UNTIL
	.text	4,$2e,"WEND"           ; $b4 WEND
	.text	2,$9b,"BY"             ; $b5 BY
	.text	4,$1c,"CALL"           ; $b6 CALL
	.text	6,$b2,"CIRCLE"         ; $b7 CIRCLE
	.text	5,$67,"CLEAR"          ; $b8 CLEAR
	.text	5,$7f,"COLOR"          ; $b9 COLOR
	.text	6,$d4,"COLOUR"         ; $ba COLOUR
	.text	4,$1a,"DATA"           ; $bb DATA
	.text	3,$da,"DIM"            ; $bc DIM
	.text	6,$db,"DOWNTO"         ; $bd DOWNTO
	.text	4,$29,"ELSE"           ; $be ELSE
	.text	4,$34,"FROM"           ; $bf FROM
	.text	3,$e5,"GFX"            ; $c0 GFX
	.text	4,$24,"HERE"           ; $c1 HERE
	.text	5,$63,"IMAGE"          ; $c2 IMAGE
	.text	3,$e5,"LET"            ; $c3 LET
	.text	4,$28,"LINE"           ; $c4 LINE
	.text	5,$6b,"LOCAL"          ; $c5 LOCAL
	.text	3,$db,"OFF"            ; $c6 OFF
	.text	2,$9d,"ON"             ; $c7 ON
	.text	7,$20,"OUTLINE"        ; $c8 OUTLINE
	.text	7,$0f,"PALETTE"        ; $c9 PALETTE
	.text	4,$3f,"PLOT"           ; $ca PLOT
	.text	4,$2f,"POKE"           ; $cb POKE
	.text	5,$73,"POKED"          ; $cc POKED
	.text	5,$7b,"POKEL"          ; $cd POKEL
	.text	5,$86,"POKEW"          ; $ce POKEW
	.text	4,$1c,"READ"           ; $cf READ
	.text	4,$2e,"RECT"           ; $d0 RECT
	.text	3,$e4,"REM"            ; $d1 REM
	.text	5,$7b,"SOLID"          ; $d2 SOLID
	.text	5,$89,"SOUND"          ; $d3 SOUND
	.text	6,$d7,"SPRITE"         ; $d4 SPRITE
	.text	4,$45,"TEXT"           ; $d5 TEXT
	.text	2,$a3,"TO"             ; $d6 TO
	.text	$FF
KeywordSet1:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	8,$4c,"ASSEMBLE"       ; $83 ASSEMBLE
	.text	6,$d2,"ASSERT"         ; $84 ASSERT
	.text	6,$bd,"BITMAP"         ; $85 BITMAP
	.text	5,$62,"BLOAD"          ; $86 BLOAD
	.text	5,$71,"BSAVE"          ; $87 BSAVE
	.text	3,$e2,"CLS"            ; $88 CLS
	.text	6,$d0,"CPRINT"         ; $89 CPRINT
	.text	3,$df,"DIR"            ; $8a DIR
	.text	5,$7a,"DRIVE"          ; $8b DRIVE
	.text	3,$d7,"END"            ; $8c END
	.text	7,$11,"EXPLODE"        ; $8d EXPLODE
	.text	2,$96,"GO"             ; $8e GO
	.text	5,$80,"GOSUB"          ; $8f GOSUB
	.text	4,$39,"GOTO"           ; $90 GOTO
	.text	5,$70,"HIMEM"          ; $91 HIMEM
	.text	5,$90,"INPUT"          ; $92 INPUT
	.text	4,$3c,"LIST"           ; $93 LIST
	.text	4,$20,"LOAD"           ; $94 LOAD
	.text	3,$ea,"NEW"            ; $95 NEW
	.text	4,$2e,"PING"           ; $96 PING
	.text	5,$8d,"PRINT"          ; $97 PRINT
	.text	7,$24,"RESTORE"        ; $98 RESTORE
	.text	6,$e0,"RETURN"         ; $99 RETURN
	.text	3,$f5,"RUN"            ; $9a RUN
	.text	4,$2f,"SAVE"           ; $9b SAVE
	.text	7,$0a,"SETDATE"        ; $9c SETDATE
	.text	7,$1b,"SETTIME"        ; $9d SETTIME
	.text	5,$8d,"SHOOT"          ; $9e SHOOT
	.text	7,$2a,"SPRITES"        ; $9f SPRITES
	.text	4,$46,"STOP"           ; $a0 STOP
	.text	6,$d5,"VERIFY"         ; $a1 VERIFY
	.text	3,$ee,"XGO"            ; $a2 XGO
	.text	5,$78,"XLOAD"          ; $a3 XLOAD
	.text	3,$eb,"ZAP"            ; $a4 ZAP
	.text	$FF
KeywordSet2:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	3,$c8,"ADC"            ; $83 ADC
	.text	3,$d3,"AND"            ; $84 AND
	.text	3,$e0,"ASL"            ; $85 ASL
	.text	3,$c8,"BCC"            ; $86 BCC
	.text	3,$d8,"BCS"            ; $87 BCS
	.text	3,$d8,"BEQ"            ; $88 BEQ
	.text	3,$df,"BIT"            ; $89 BIT
	.text	3,$d8,"BMI"            ; $8a BMI
	.text	3,$d5,"BNE"            ; $8b BNE
	.text	3,$de,"BPL"            ; $8c BPL
	.text	3,$d5,"BRA"            ; $8d BRA
	.text	3,$df,"BRK"            ; $8e BRK
	.text	3,$db,"BVC"            ; $8f BVC
	.text	3,$eb,"BVS"            ; $90 BVS
	.text	3,$d2,"CLC"            ; $91 CLC
	.text	3,$d3,"CLD"            ; $92 CLD
	.text	3,$d8,"CLI"            ; $93 CLI
	.text	3,$e5,"CLV"            ; $94 CLV
	.text	3,$e0,"CMP"            ; $95 CMP
	.text	3,$eb,"CPX"            ; $96 CPX
	.text	3,$ec,"CPY"            ; $97 CPY
	.text	3,$cc,"DEC"            ; $98 DEC
	.text	3,$e1,"DEX"            ; $99 DEX
	.text	3,$e2,"DEY"            ; $9a DEY
	.text	3,$e6,"EOR"            ; $9b EOR
	.text	3,$da,"INC"            ; $9c INC
	.text	3,$ef,"INX"            ; $9d INX
	.text	3,$f0,"INY"            ; $9e INY
	.text	3,$e7,"JMP"            ; $9f JMP
	.text	3,$ef,"JSR"            ; $a0 JSR
	.text	3,$d1,"LDA"            ; $a1 LDA
	.text	3,$e8,"LDX"            ; $a2 LDX
	.text	3,$e9,"LDY"            ; $a3 LDY
	.text	3,$f1,"LSR"            ; $a4 LSR
	.text	3,$ed,"NOP"            ; $a5 NOP
	.text	3,$e2,"ORA"            ; $a6 ORA
	.text	3,$d9,"PHA"            ; $a7 PHA
	.text	3,$e8,"PHP"            ; $a8 PHP
	.text	3,$f0,"PHX"            ; $a9 PHX
	.text	3,$f1,"PHY"            ; $aa PHY
	.text	3,$dd,"PLA"            ; $ab PLA
	.text	3,$ec,"PLP"            ; $ac PLP
	.text	3,$f4,"PLX"            ; $ad PLX
	.text	3,$f5,"PLY"            ; $ae PLY
	.text	3,$ed,"ROL"            ; $af ROL
	.text	3,$f3,"ROR"            ; $b0 ROR
	.text	3,$ef,"RTI"            ; $b1 RTI
	.text	3,$f9,"RTS"            ; $b2 RTS
	.text	3,$d8,"SBC"            ; $b3 SBC
	.text	3,$db,"SEC"            ; $b4 SEC
	.text	3,$dc,"SED"            ; $b5 SED
	.text	3,$e1,"SEI"            ; $b6 SEI
	.text	3,$e8,"STA"            ; $b7 STA
	.text	3,$f7,"STP"            ; $b8 STP
	.text	3,$ff,"STX"            ; $b9 STX
	.text	3,$00,"STY"            ; $ba STY
	.text	3,$01,"STZ"            ; $bb STZ
	.text	3,$ed,"TAX"            ; $bc TAX
	.text	3,$ee,"TAY"            ; $bd TAY
	.text	3,$e8,"TRB"            ; $be TRB
	.text	3,$e9,"TSB"            ; $bf TSB
	.text	3,$ff,"TSX"            ; $c0 TSX
	.text	3,$ed,"TXA"            ; $c1 TXA
	.text	3,$ff,"TXS"            ; $c2 TXS
	.text	3,$ee,"TYA"            ; $c3 TYA
	.text	$FF
	.send code
