;
;	This is automatically generated.
;
	.section code
KeywordSet0:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	4,$fe,"ABS("           ; $83 ABS(
	.text	6,$93,"ALLOC("         ; $84 ALLOC(
	.text	4,$ff,"ASC("           ; $85 ASC(
	.text	5,$29,"CHR$("          ; $86 CHR$(
	.text	5,$41,"DEEK("          ; $87 DEEK(
	.text	6,$aa,"EVENT("         ; $88 EVENT(
	.text	5,$6b,"FALSE"          ; $89 FALSE
	.text	5,$44,"FRAC("          ; $8a FRAC(
	.text	4,$0d,"HIT("           ; $8b HIT(
	.text	4,$13,"INT("           ; $8c INT(
	.text	6,$a7,"ISVAL("         ; $8d ISVAL(
	.text	5,$5c,"JOYB("          ; $8e JOYB(
	.text	5,$72,"JOYX("          ; $8f JOYX(
	.text	5,$73,"JOYY("          ; $90 JOYY(
	.text	6,$77,"LEFT$("         ; $91 LEFT$(
	.text	4,$07,"LEN("           ; $92 LEN(
	.text	4,$0e,"MAX("           ; $93 MAX(
	.text	5,$26,"MID$("          ; $94 MID$(
	.text	4,$0c,"MIN("           ; $95 MIN(
	.text	4,$19,"NOT("           ; $96 NOT(
	.text	5,$4d,"PEEK("          ; $97 PEEK(
	.text	8,$3c,"PLAYING("       ; $98 PLAYING(
	.text	7,$e9,"RANDOM("        ; $99 RANDOM(
	.text	7,$ca,"RIGHT$("        ; $9a RIGHT$(
	.text	4,$0c,"RND("           ; $9b RND(
	.text	4,$10,"SGN("           ; $9c SGN(
	.text	4,$0e,"SPC("           ; $9d SPC(
	.text	5,$45,"STR$("          ; $9e STR$(
	.text	6,$a9,"TIMER("         ; $9f TIMER(
	.text	4,$40,"TRUE"           ; $a0 TRUE
	.text	4,$0b,"VAL("           ; $a1 VAL(
	.text	3,$e7,"FOR"            ; $a2 FOR
	.text	2,$8f,"IF"             ; $a3 IF
	.text	4,$34,"PROC"           ; $a4 PROC
	.text	6,$c1,"REPEAT"         ; $a5 REPEAT
	.text	5,$79,"WHILE"          ; $a6 WHILE
	.text	5,$66,"ENDIF"          ; $a7 ENDIF
	.text	7,$0b,"ENDPROC"        ; $a8 ENDPROC
	.text	4,$3f,"NEXT"           ; $a9 NEXT
	.text	4,$2f,"THEN"           ; $aa THEN
	.text	5,$8c,"UNTIL"          ; $ab UNTIL
	.text	4,$2e,"WEND"           ; $ac WEND
	.text	2,$9b,"BY"             ; $ad BY
	.text	4,$1c,"CALL"           ; $ae CALL
	.text	6,$b2,"CIRCLE"         ; $af CIRCLE
	.text	5,$67,"CLEAR"          ; $b0 CLEAR
	.text	3,$e2,"CLS"            ; $b1 CLS
	.text	5,$7f,"COLOR"          ; $b2 COLOR
	.text	6,$d4,"COLOUR"         ; $b3 COLOUR
	.text	4,$1a,"DATA"           ; $b4 DATA
	.text	3,$da,"DIM"            ; $b5 DIM
	.text	4,$23,"DOKE"           ; $b6 DOKE
	.text	6,$db,"DOWNTO"         ; $b7 DOWNTO
	.text	4,$29,"ELSE"           ; $b8 ELSE
	.text	4,$34,"FROM"           ; $b9 FROM
	.text	3,$e5,"GFX"            ; $ba GFX
	.text	5,$80,"GOSUB"          ; $bb GOSUB
	.text	4,$39,"GOTO"           ; $bc GOTO
	.text	4,$24,"HERE"           ; $bd HERE
	.text	5,$63,"IMAGE"          ; $be IMAGE
	.text	5,$90,"INPUT"          ; $bf INPUT
	.text	3,$e5,"LET"            ; $c0 LET
	.text	4,$28,"LINE"           ; $c1 LINE
	.text	5,$6b,"LOCAL"          ; $c2 LOCAL
	.text	3,$db,"OFF"            ; $c3 OFF
	.text	2,$9d,"ON"             ; $c4 ON
	.text	7,$20,"OUTLINE"        ; $c5 OUTLINE
	.text	7,$0f,"PALETTE"        ; $c6 PALETTE
	.text	4,$3f,"PLOT"           ; $c7 PLOT
	.text	4,$2f,"POKE"           ; $c8 POKE
	.text	5,$8d,"PRINT"          ; $c9 PRINT
	.text	4,$1c,"READ"           ; $ca READ
	.text	4,$2e,"RECT"           ; $cb RECT
	.text	3,$e4,"REM"            ; $cc REM
	.text	6,$e0,"RETURN"         ; $cd RETURN
	.text	5,$7b,"SOLID"          ; $ce SOLID
	.text	5,$89,"SOUND"          ; $cf SOUND
	.text	6,$d7,"SPRITE"         ; $d0 SPRITE
	.text	4,$45,"TEXT"           ; $d1 TEXT
	.text	2,$a3,"TO"             ; $d2 TO
	.text	$FF
KeywordSet1:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	8,$4c,"ASSEMBLE"       ; $83 ASSEMBLE
	.text	6,$d2,"ASSERT"         ; $84 ASSERT
	.text	6,$bd,"BITMAP"         ; $85 BITMAP
	.text	3,$d7,"END"            ; $86 END
	.text	7,$11,"EXPLODE"        ; $87 EXPLODE
	.text	2,$96,"GO"             ; $88 GO
	.text	4,$3c,"LIST"           ; $89 LIST
	.text	4,$20,"LOAD"           ; $8a LOAD
	.text	3,$ea,"NEW"            ; $8b NEW
	.text	4,$2e,"PING"           ; $8c PING
	.text	7,$24,"RESTORE"        ; $8d RESTORE
	.text	3,$f5,"RUN"            ; $8e RUN
	.text	5,$8d,"SHOOT"          ; $8f SHOOT
	.text	7,$2a,"SPRITES"        ; $90 SPRITES
	.text	4,$46,"STOP"           ; $91 STOP
	.text	3,$eb,"ZAP"            ; $92 ZAP
	.text	$FF
KeywordSet2:
	.text	0,$65,""               ; $80 !0:EOF
	.text	0,$58,""               ; $81 !1:SH1
	.text	0,$5a,""               ; $82 !2:SH2
	.text	3,$c8,"ADC"            ; $83 ADC
	.text	3,$d3,"AND"            ; $84 AND
	.text	3,$e0,"ASL"            ; $85 ASL
	.text	3,$c8,"BCC"            ; $86 BCC
	.text	3,$d8,"BCS"            ; $87 BCS
	.text	3,$d8,"BEQ"            ; $88 BEQ
	.text	3,$df,"BIT"            ; $89 BIT
	.text	3,$d8,"BMI"            ; $8a BMI
	.text	3,$d5,"BNE"            ; $8b BNE
	.text	3,$de,"BPL"            ; $8c BPL
	.text	3,$d5,"BRA"            ; $8d BRA
	.text	3,$df,"BRK"            ; $8e BRK
	.text	3,$db,"BVC"            ; $8f BVC
	.text	3,$eb,"BVS"            ; $90 BVS
	.text	3,$d2,"CLC"            ; $91 CLC
	.text	3,$d3,"CLD"            ; $92 CLD
	.text	3,$d8,"CLI"            ; $93 CLI
	.text	3,$e5,"CLV"            ; $94 CLV
	.text	3,$e0,"CMP"            ; $95 CMP
	.text	3,$eb,"CPX"            ; $96 CPX
	.text	3,$ec,"CPY"            ; $97 CPY
	.text	3,$cc,"DEC"            ; $98 DEC
	.text	3,$e1,"DEX"            ; $99 DEX
	.text	3,$e2,"DEY"            ; $9a DEY
	.text	3,$e6,"EOR"            ; $9b EOR
	.text	3,$da,"INC"            ; $9c INC
	.text	3,$ef,"INX"            ; $9d INX
	.text	3,$f0,"INY"            ; $9e INY
	.text	3,$e7,"JMP"            ; $9f JMP
	.text	3,$ef,"JSR"            ; $a0 JSR
	.text	3,$d1,"LDA"            ; $a1 LDA
	.text	3,$e8,"LDX"            ; $a2 LDX
	.text	3,$e9,"LDY"            ; $a3 LDY
	.text	3,$f1,"LSR"            ; $a4 LSR
	.text	3,$ed,"NOP"            ; $a5 NOP
	.text	3,$e2,"ORA"            ; $a6 ORA
	.text	3,$d9,"PHA"            ; $a7 PHA
	.text	3,$e8,"PHP"            ; $a8 PHP
	.text	3,$f0,"PHX"            ; $a9 PHX
	.text	3,$f1,"PHY"            ; $aa PHY
	.text	3,$dd,"PLA"            ; $ab PLA
	.text	3,$ec,"PLP"            ; $ac PLP
	.text	3,$f4,"PLX"            ; $ad PLX
	.text	3,$f5,"PLY"            ; $ae PLY
	.text	3,$ed,"ROL"            ; $af ROL
	.text	3,$f3,"ROR"            ; $b0 ROR
	.text	3,$ef,"RTI"            ; $b1 RTI
	.text	3,$f9,"RTS"            ; $b2 RTS
	.text	3,$d8,"SBC"            ; $b3 SBC
	.text	3,$db,"SEC"            ; $b4 SEC
	.text	3,$dc,"SED"            ; $b5 SED
	.text	3,$e1,"SEI"            ; $b6 SEI
	.text	3,$e8,"STA"            ; $b7 STA
	.text	3,$f7,"STP"            ; $b8 STP
	.text	3,$ff,"STX"            ; $b9 STX
	.text	3,$00,"STY"            ; $ba STY
	.text	3,$01,"STZ"            ; $bb STZ
	.text	3,$ed,"TAX"            ; $bc TAX
	.text	3,$ee,"TAY"            ; $bd TAY
	.text	3,$e8,"TRB"            ; $be TRB
	.text	3,$e9,"TSB"            ; $bf TSB
	.text	3,$ff,"TSX"            ; $c0 TSX
	.text	3,$ed,"TXA"            ; $c1 TXA
	.text	3,$ff,"TXS"            ; $c2 TXS
	.text	3,$ee,"TYA"            ; $c3 TYA
	.text	$FF
	.send code
