;
;	This file is automatically generated
;
GRVectorTable:
	.word	GRUndefined              ; $00
	.word	GRUndefined              ; $01
	.word	GXClearBitmap            ; $02 Clear
	.word	GXSetColourMode          ; $03 Colour
	.word	GXFontHandler            ; $04 DrawFont
	.word	GXSpriteHandler          ; $05 DrawSprite
	.word	GRUndefined              ; $06
	.word	GRUndefined              ; $07
	.word	GRUndefined              ; $08
	.word	GRUndefined              ; $09
	.word	GRUndefined              ; $0a
	.word	GRUndefined              ; $0b
	.word	GRUndefined              ; $0c
	.word	GRUndefined              ; $0d
	.word	GRUndefined              ; $0e
	.word	GRUndefined              ; $0f
	.word	GXMove                   ; $10 Move
	.word	GXLine                   ; $11 Line
	.word	GXFrameRectangle         ; $12 FrameRect
	.word	GXFillRectangle          ; $13 FillRect
	.word	GXFrameCircle            ; $14 FrameCircle
	.word	GXFillCircle             ; $15 FillCircle
	.word	GRUndefined              ; $16
	.word	GRUndefined              ; $17
	.word	GXPlotPoint              ; $18 Plot
	.word	GRUndefined              ; $19
	.word	GRUndefined              ; $1a
	.word	GRUndefined              ; $1b
	.word	GRUndefined              ; $1c
	.word	GRUndefined              ; $1d
	.word	GRUndefined              ; $1e
	.word	GRUndefined              ; $1f
