;
;	This file is automatically generated
;

GRFirstFreeCode = 26

GRVectorTable:
	.word	GXInitialise             ; $00 Initialise
	.word	GXControlBitmap          ; $01 BITMAPCTL
	.word	GXControlSprite          ; $02 SPRITECTL
	.word	GXClearBitmap            ; $03 Clear
	.word	GXSetColourMode          ; $04 Colour
	.word	GXFontHandler            ; $05 DrawFont
	.word	GXSpriteHandler          ; $06 DrawSprite
	.word	GXSelect                 ; $07 SPRUSE
	.word	GXSelectImage            ; $08 SPRIMG
	.word	GRUndefined              ; $09
	.word	GRUndefined              ; $0a
	.word	GRUndefined              ; $0b
	.word	GRUndefined              ; $0c
	.word	GRUndefined              ; $0d
	.word	GRUndefined              ; $0e
	.word	GRUndefined              ; $0f
	.word	GXMove                   ; $10 Move
	.word	GXLine                   ; $11 Line
	.word	GXFrameRectangle         ; $12 FrameRect
	.word	GXFillRectangle          ; $13 FillRect
	.word	GXFrameCircle            ; $14 FrameCircle
	.word	GXFillCircle             ; $15 FillCircle
	.word	GRUndefined              ; $16
	.word	GRUndefined              ; $17
	.word	GXPlotPoint              ; $18 Plot
	.word	GXMoveSprite             ; $19 SPRMOVE
