# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		constants.py
#		Purpose :	Calculate constants.
#		Date :		23rd September 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math

def convert(decimal):
	exponent = int(math.log(decimal,2))
	mantissa = decimal / pow(2,exponent)
	while mantissa < 0x40000000:
		mantissa *= 2 
		exponent -= 1
	mantissa = int(mantissa+0.5)
	return [mantissa,exponent & 0xFF]

h = open("common/generated/constants.asm","w")
h.write(";\n;\tThis file is automatically generated.\n;\n")
h.write(".section code\n")
h.write("DecimalScalarTable:\n")
for i in range(1,12):
	decimal = 1.0 / pow(10,i)
	ed = convert(decimal)
	h.write("\t.dword ${0:08x} ; {1}\n".format(ed[0],decimal))
	h.write("\t.byte ${0:02x}\n".format(ed[1]))
h.write(".send code\n")

h.close()	
