# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		makebuild.py
#		Purpose :	Build the build file from asm/inc
#		Date :		18th September 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys
#
#		Sort by module name - e.g. without the first directory
#
def sortKey(k):
	k = ":".join(k.split(os.sep)[2:])
	return(k)
#
#		Get a list of files involved
#
includeFiles = []																			# include files in order
sourceFiles = []																			# source files in order

for root,dirs,files in os.walk("."): 														# scan for directories
	for f in files: 																		# look for files that are .inc or .asm
		if f.find("_") < 0:
			fName = root + os.sep + f
			if fName.endswith(".asm"):
				sourceFiles.append(fName)
			if fName.endswith(".inc"):
				includeFiles.append(fName)

includeFiles.sort(key = lambda k:sortKey(k))
sourceFiles.sort(key = lambda k:sortKey(k))

for s in sys.argv[1:]:
	sourceFiles.append("../modules/_build/{0}.module".format(s))

#
#		Create the composite file to build the whole thing.
#
h = open("_basic.asm","w") 																	# create the build file.
h.write(";\n;\tThis file is automatically generated\n;\n")  								# output the build file

for f in includeFiles:
	h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep,"/")))
h.write("\n\n")
for f in sourceFiles:
	h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep,"/")))
h.close()