"""Build the SuperBASIC composite assembly file from `.asm`/`.inc` sources."""

import os
import sys


#
# Sort by module name - e.g. without the first directory
#
def sortKey(k):
    k = ":".join(k.split(os.sep)[2:])
    return k


#
# Get a list of files involved
#
includeFiles = []  # include files in order
sourceFiles = []  # source files in order
moduleFiles = []
page2ModuleFiles = []

modulesIntegrated = {}

for s in sys.argv[1:]:
    if s[0] == "+":
        name = s[1:]
        if ":" in name:
            name, page_str = name.split(":", 1)
            if page_str == "2":
                page2ModuleFiles.append("../modules/.build/{0}_p2.module.asm".format(name))
                modulesIntegrated[name] = True
                continue
        moduleFiles.append("../modules/.build/{0}.module.asm".format(name))
        modulesIntegrated[name] = True
    else:
        moduleFiles.append("!{0}Integrated = 0".format(s[1:]))

for root, dirs, files in os.walk("."):  # scan for directories
    for f in files:  # look for files that are .inc or .asm
        if f.find("_") < 0:
            fName = root + os.sep + f
            reject = False
            pos = root.find("module.interface")
            if pos >= 0:  # if module.interface.<something>
                interface = root[pos:].split(os.sep)[
                    1
                ]  # check we are using this module
                reject = interface not in modulesIntegrated

            if not reject:
                if fName.endswith(".asm"):
                    sourceFiles.append(fName)
                if fName.endswith(".inc"):
                    includeFiles.append(fName)

includeFiles.sort(key=lambda k: sortKey(k))
sourceFiles.sort(key=lambda k: sortKey(k))

#
# Create the composite file to build the whole thing.
#
h = open("_basic.asm", "w")  # create the build file.
h.write(";\n;\tThis file is automatically generated\n;\n")  # output the build file

for f in includeFiles:
    h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep, "/")))
h.write("\n\n")
for f in sourceFiles:
    h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep, "/")))
h.write("\n\n")


h.write(".section code\n")
h.write("StartModuleCode:\n")
h.write("\t.if PagingEnabled==1\n")
h.write("\t* = $A000\n")
h.write("\t.offs $2000\n")
h.write("\t.endif\n")
h.write(".send code\n")

for f in moduleFiles:
    if f.startswith("!"):
        h.write("\t{0}\n".format(f[1:]))
    else:
        h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep, "/")))

h.write('\n; --- Header data in boot section ($6000-$7FFF) ---\n')
h.write('\t.include\t"../modules/hardware/header/.build/headerdata.dat"\n')

if page2ModuleFiles:
    h.write("\n; --- Module page 2 ---\n")
    h.write("; page2 section at $4000 (below boot section at $6000)\n")
    h.write("; .logical * + $6000 in each block maps labels to $A000+ runtime addresses\n")
    for f in page2ModuleFiles:
        h.write('\t.include\t"{0}"\n'.format(f.replace(os.sep, "/")))

h.close()
