# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		timestamp.py
#		Purpose :	Output assembly timestamp
#		Date :		5th October 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,datetime

h = open("scripts/buildcount.txt")
buildCount = int(h.read(-1))
h.close()

h = open("scripts/buildcount.txt","w")
h.write("{0}\n".format(buildCount+1))
h.close()

time = datetime.datetime.now()
build = time.strftime("%A %d-%b-%Y")
h = open("common/generated/timestamp.asm","w")
h.write(";\n;\tThis file is automatically generated.\n;\n")
h.write("\t.text \"Built {0}. Build {1}.\"\n".format(build,buildCount))
h.close()	
