# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		timestamp.py
#		Purpose :	Output assembly timestamp
#		Date :		5th October 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,datetime

h = open("scripts/buildcount.txt")
buildCount = int(h.read(-1))+1
h.close()

h = open("scripts/buildcount.txt","w")
h.write("{0}\n".format(buildCount))
h.close()

time = datetime.datetime.now()
build = time.strftime("(%d-%b-%y)")
h = open("common/generated/timestamp.asm","w")
h.write(";\n;\tThis file is automatically generated.\n;\n")
h.write(".section code\n")
h.write("\t.text \"Release Alpha {1} {0}. \"\n".format(build,buildCount))
h.write(".send code\n")
h.close()	
