PagingEnabled = 1
	.if hardwareIntegrated == 1
EXTPrintCharacter:
	inc 8+5
	jsr	Export_EXTPrintCharacter
	php
	dec 8+5
	plp
	rts
EXTPrintNoControl:
	inc 8+5
	jsr	Export_EXTPrintNoControl
	php
	dec 8+5
	plp
	rts
EXTInitialise:
	inc 8+5
	jsr	Export_EXTInitialise
	php
	dec 8+5
	plp
	rts
EXTReadController:
	inc 8+5
	jsr	Export_EXTReadController
	php
	dec 8+5
	plp
	rts
EXTInputLine:
	inc 8+5
	jsr	Export_EXTInputLine
	php
	dec 8+5
	plp
	rts
	.endif
	.if kernelIntegrated == 1
KNLInputSingleCharacter:
	inc 8+5
	jsr	Export_KNLInputSingleCharacter
	php
	dec 8+5
	plp
	rts
KNLOpenFileRead:
	inc 8+5
	jsr	Export_KNLOpenFileRead
	php
	dec 8+5
	plp
	rts
KNLOpenFileWrite:
	inc 8+5
	jsr	Export_KNLOpenFileWrite
	php
	dec 8+5
	plp
	rts
KNLReadByteInit:
	inc 8+5
	jsr	Export_KNLReadByteInit
	php
	dec 8+5
	plp
	rts
KNLReadByte:
	inc 8+5
	jsr	Export_KNLReadByte
	php
	dec 8+5
	plp
	rts
KNLReadBlock:
	inc 8+5
	jsr	Export_KNLReadBlock
	php
	dec 8+5
	plp
	rts
KNLWriteBlock:
	inc 8+5
	jsr	Export_KNLWriteBlock
	php
	dec 8+5
	plp
	rts
KNLCloseFile:
	inc 8+5
	jsr	Export_KNLCloseFile
	php
	dec 8+5
	plp
	rts
	.endif
	.if graphicsIntegrated == 1
GXGraphicDraw:
	inc 8+5
	jsr	Export_GXGraphicDraw
	php
	dec 8+5
	plp
	rts
	.endif
	.if soundIntegrated == 1
SNDCommand:
	inc 8+5
	jsr	Export_SNDCommand
	php
	dec 8+5
	plp
	rts
SNDUpdate:
	inc 8+5
	jsr	Export_SNDUpdate
	php
	dec 8+5
	plp
	rts
	.endif
	.if tokeniserIntegrated == 1
TKListConvertLine:
	inc 8+5
	jsr	Export_TKListConvertLine
	php
	dec 8+5
	plp
	rts
TKTokeniseLine:
	inc 8+5
	jsr	Export_TKTokeniseLine
	php
	dec 8+5
	plp
	rts
	.endif
