PagingEnabled = 1
	.if hardwareIntegrated == 1
EXTPrintCharacter:
	inc 8+5
	jsr	Export_EXTPrintCharacter
	php
	dec 8+5
	plp
	rts
EXTPrintNoControl:
	inc 8+5
	jsr	Export_EXTPrintNoControl
	php
	dec 8+5
	plp
	rts
EXTInitialise:
	inc 8+5
	jsr	Export_EXTInitialise
	php
	dec 8+5
	plp
	rts
	.endif
	.if graphicsIntegrated == 1
GXGraphicDraw:
	inc 8+5
	jsr	Export_GXGraphicDraw
	php
	dec 8+5
	plp
	rts
	.endif
	.if soundIntegrated == 1
SNDCommand:
	inc 8+5
	jsr	Export_SNDCommand
	php
	dec 8+5
	plp
	rts
SNDUpdate:
	inc 8+5
	jsr	Export_SNDUpdate
	php
	dec 8+5
	plp
	rts
	.endif
	.if tokeniserIntegrated == 1
TKListConvertLine:
	inc 8+5
	jsr	Export_TKListConvertLine
	php
	dec 8+5
	plp
	rts
TKTokeniseLine:
	inc 8+5
	jsr	Export_TKTokeniseLine
	php
	dec 8+5
	plp
	rts
TKInitialise:
	inc 8+5
	jsr	Export_TKInitialise
	php
	dec 8+5
	plp
	rts
	.endif
