;
;	This file is automatically generated
;
	.include	"./aa_system/01common.inc"
	.include	"./aa_system/02macros.inc"
	.include	"./aa_system/03access.inc"
	.include	"./aa_system/04data.inc"
	.include	"./generated/kwdconst.inc"
	.include	"./aa_system/00start.asm"
	.include	"./commands/clear.asm"
	.include	"./commands/end.asm"
	.include	"./commands/new.asm"
	.include	"./tokeniser/backload.asm"
