;
;	This file is automatically generated
;
	.include	"./system/01common.inc"
	.include	"./system/02macros.inc"
	.include	"./system/03access.inc"
	.include	"./system/04data.inc"
	.include	"./system/00start.asm"
